### ISSUE TITLE
PowerShell script no longer works now that beta endpoint is on a separate module

### ISSUE THREAD

**Issue by Wollycobbles** [AzureAD/entra-id-inbound-provisioning#5]
Get-MgProfile is now not included with the updated graph modules.  This halts the script dead.

![image](https://github.com/AzureAD/entra-id-inbound-provisioning/assets/142597915/4bc01c5d-655f-4fef-8c41-2eb573bd99dd)

**Comment by cmmdesai** [comment]
@Wollycobbles Thank you for reporting this issue. We've fixed this issue. Can you test and confirm that the script works for you?

**Comment by cmmdesai** [comment]
Closing the issue as we're no longer observing this.
